/**
 * One Message
 * One Message用API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ユーザー情報
 */
export interface GetMeResponse { 
    /**
     * ID
     */
    id: string;
    /**
     * ニックネーム
     */
    name?: string;
    /**
     * メールアドレス
     */
    email?: string;
}

