/**
 * One Message
 * One Message用API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 初期登録時のユーザー情報
 */
export interface LoginRequest { 
    /**
     * メールアドレス
     */
    email: string;
    /**
     * パスワード
     */
    password: string;
}

